=== akconcerts/events/schema/event.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "AK Concert Event Schema",
  "type": "object",
  "required": ["id", "date", "city", "venue", "category", "title"],
  "properties": {
    "id": {
      "type": "string",
      "description": "Unique identifier for the event"
    },
    "date": {
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}$",
      "description": "Event date in YYYY-MM-DD format"
    },
    "city": {
      "type": "string",
      "description": "Alaskan city where event takes place"
    },
    "venue": {
      "type": "string",
      "description": "Venue name"
    },
    "category": {
      "type": "string",
      "enum": ["music", "comedy", "dance", "theatre", "community", "festival"],
      "description": "Event category"
    },
    "title": {
      "type": "string",
      "description": "Event title or performing artist/band name"
    },
    "time": {
      "type": "string",
      "description": "Event start/end time"
    },
    "ticketUrl": {
      "type": "string",
      "description": "URL to ticket purchase or details page"
    },
    "cost": {
      "type": "string",
      "description": "Ticket price or admission cost"
    }
  }
}

=== akconcerts/events/cities/barrow.json
[
  {
    "id": "26346",
    "date": "2024-05-01",
    "city": "Barrow",
    "venue": "Fred Ipalook Elementary School",
    "category": "music",
    "title": "2024 Commencement",
    "time": "3p-5p",
    "ticketUrl": "https://www.facebook.com/events/1184597849388188/?acontext=%7B%22event_action_history%22%3A%5b%7B%22mechanism%22%3A%22search_results%22%2C%22surface%22%3A%22bookmark_search%22%7D%5d%2C%22ref_notif_type%22%3Anull%7D",
    "cost": ""
  },
  {
    "id": "43690",
    "date": "2026-04-29",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Teen Art Saturdays",
    "time": "3p-5p",
    "ticketUrl": "https://www.facebook.com/events/2272721403136396/2280216412386895/?acontext=%7B%22event_action_history%22%3A%5b%7B%22mechanism%22%3A%22surface%22%2C%22surface%22%3A%22permalink%22%7D%5d%2C%22ref_notif_type%22%3Anull%7D",
    "cost": ""
  },
  {
    "id": "43920",
    "date": "2026-05-06",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Teen Art Saturdays",
    "time": "3p-5p",
    "ticketUrl": "https://www.facebook.com/events/2272721403136396/2280216409053562/?acontext=%7B%22event_action_history%22%3A%5b%7B%22extra_data%22%3A%22%22%2C%22mechanism%22%3A%22surface%22%2C%22surface%22%3A%22permalink%22%7D%2C%7B%22extra_data%22%3A%22%22%2C%22me",
    "cost": ""
  },
  {
    "id": "44141",
    "date": "2026-05-13",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-3p",
    "ticketUrl": "https://www.facebook.com/events/2139971986761030/2139972016761027/",
    "cost": ""
  },
  {
    "id": "44359",
    "date": "2026-05-20",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-3p",
    "ticketUrl": "https://www.facebook.com/events/2139971986761030/2139971993427696/?active_tab=about",
    "cost": ""
  },
  {
    "id": "44576",
    "date": "2026-05-27",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-3p",
    "ticketUrl": "https://www.facebook.com/events/2139971986761030/2139972020094360/?active_tab=about",
    "cost": ""
  },
  {
    "id": "44806",
    "date": "2026-06-03",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-3p",
    "ticketUrl": "https://www.facebook.com/events/2139971986761030/2139972013427694/?acontext=%7B%22event_action_history%22%3A%5b%7B%22mechanism%22%3A%22surface%22%2C%22surface%22%3A%22permalink%22%7D%5d%2C%22ref_notif_type%22%3Anull%7D",
    "cost": ""
  },
  {
    "id": "45070",
    "date": "2026-06-10",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-3p",
    "ticketUrl": "https://www.facebook.com/TuzzyConsortiumLibrary/",
    "cost": ""
  },
  {
    "id": "45343",
    "date": "2026-06-17",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-3p",
    "ticketUrl": "https://www.facebook.com/TuzzyConsortiumLibrary/",
    "cost": ""
  },
  {
    "id": "45655",
    "date": "2026-06-24",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-3p",
    "ticketUrl": "https://www.facebook.com/TuzzyConsortiumLibrary/",
    "cost": ""
  },
  {
    "id": "45996",
    "date": "2026-07-01",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-3p",
    "ticketUrl": "https://www.facebook.com/TuzzyConsortiumLibrary/",
    "cost": ""
  },
  {
    "id": "46274",
    "date": "2026-07-08",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-3p",
    "ticketUrl": "https://www.facebook.com/TuzzyConsortiumLibrary/",
    "cost": ""
  },
  {
    "id": "46551",
    "date": "2026-07-15",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-3p",
    "ticketUrl": "https://www.facebook.com/TuzzyConsortiumLibrary/",
    "cost": ""
  },
  {
    "id": "46845",
    "date": "2026-07-18",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-3p",
    "ticketUrl": "https://www.facebook.com/TuzzyConsortiumLibrary/",
    "cost": ""
  },
  {
    "id": "47026",
    "date": "2026-07-22",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-3p",
    "ticketUrl": "https://www.facebook.com/TuzzyConsortiumLibrary/",
    "cost": ""
  },
  {
    "id": "47220",
    "date": "2026-07-29",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-3p",
    "ticketUrl": "https://www.facebook.com/TuzzyConsortiumLibrary/",
    "cost": ""
  },
  {
    "id": "47381",
    "date": "2026-08-05",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-3p",
    "ticketUrl": "https://www.facebook.com/TuzzyConsortiumLibrary/",
    "cost": ""
  },
  {
    "id": "47582",
    "date": "2026-08-08",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-3p",
    "ticketUrl": "https://www.facebook.com/TuzzyConsortiumLibrary/",
    "cost": ""
  },
  {
    "id": "47748",
    "date": "2026-08-12",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-3p",
    "ticketUrl": "https://www.facebook.com/TuzzyConsortiumLibrary/",
    "cost": ""
  },
  {
    "id": "48008",
    "date": "2026-08-15",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-2p",
    "ticketUrl": "",
    "cost": ""
  },
  {
    "id": "48176",
    "date": "2026-08-19",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-2p",
    "ticketUrl": "https://www.tuzzy.org/home",
    "cost": ""
  },
  {
    "id": "48581",
    "date": "2026-08-26",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-2p",
    "ticketUrl": "https://www.tuzzy.org/home",
    "cost": ""
  },
  {
    "id": "48797",
    "date": "2026-09-02",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-2p",
    "ticketUrl": "https://www.tuzzy.org/home",
    "cost": ""
  },
  {
    "id": "48977",
    "date": "2026-09-09",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-2p",
    "ticketUrl": "https://www.tuzzy.org/home",
    "cost": ""
  },
  {
    "id": "49169",
    "date": "2026-09-16",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-2p",
    "ticketUrl": "https://www.tuzzy.org/home",
    "cost": ""
  },
  {
    "id": "49360",
    "date": "2026-09-23",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-2p",
    "ticketUrl": "https://www.tuzzy.org/home",
    "cost": ""
  },
  {
    "id": "49381",
    "date": "2026-09-23",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Vampires & Chicken Nuggets: A Thematic Book Club",
    "time": "6p-7p",
    "ticketUrl": "https://www.tuzzy.org/home",
    "cost": ""
  },
  {
    "id": "49555",
    "date": "2026-09-30",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-2p",
    "ticketUrl": "https://www.tuzzy.org/home",
    "cost": ""
  },
  {
    "id": "49742",
    "date": "2026-10-07",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-2p",
    "ticketUrl": "https://www.tuzzy.org/home",
    "cost": ""
  },
  {
    "id": "49927",
    "date": "2026-10-10",
    "city": "Barrow",
    "venue": "Tuzzy Consortium Library",
    "category": "community",
    "title": "Storytime & Crafternoon",
    "time": "1p-2p",
    "ticketUrl": "https://www.tuzzy.org/home",
    "cost": ""
  }
]

=== akconcerts/events/cities/trapper-creek.json
[
  {
    "id": "47922",
    "date": "2026-08-13",
    "city": "Trapper Creek",
    "venue": "Boots Bison Ranch",
    "category": "music",
    "title": "Trapper Creek Bluegrass Revival",
    "time": "TBD",
    "ticketUrl": "",
    "cost": ""
  },
  {
    "id": "47991",
    "date": "2026-08-14",
    "city": "Trapper Creek",
    "venue": "Boots Bison Ranch",
    "category": "music",
    "title": "Trapper Creek Bluegrass Revival",
    "time": "TBD",
    "ticketUrl": "",
    "cost": ""
  },
  {
    "id": "48080",
    "date": "2026-08-15",
    "city": "Trapper Creek",
    "venue": "Boots Bison Ranch",
    "category": "music",
    "title": "Trapper Creek Bluegrass Revival",
    "time": "TBD",
    "ticketUrl": "",
    "cost": ""
  },
  {
    "id": "48117",
    "date": "2026-08-16",
    "city": "Trapper Creek",
    "venue": "Boots Bison Ranch",
    "category": "music",
    "title": "Trapper Creek Bluegrass Revival",
    "time": "TBD",
    "ticketUrl": "",
    "cost": ""
  }
]

=== akconcerts/events/cities/moose-pass.json
[
  {
    "id": "9170",
    "date": "2021-08-04",
    "city": "Moose Pass",
    "venue": "Trail Lake Lodge",
    "category": "music",
    "title": "Roses’s Pawn Shop",
    "time": "6p-9p",
    "ticketUrl": "https://www.facebook.com/photo.php?fbid=369020141453674&set=pb.100050370734796.-2207520000..&type=3",
    "cost": ""
  },
  {
    "id": "27515",
    "date": "2024-06-19",
    "city": "Moose Pass",
    "venue": "Trail Lake Lodge",
    "category": "music",
    "title": "Roland Roberts Band",
    "time": "8p-12a",
    "ticketUrl": "https://www.facebook.com/events/981846426913889",
    "cost": ""
  },
  {
    "id": "45643",
    "date": "2026-06-24",
    "city": "Moose Pass",
    "venue": "North Peninsula Recreation Area",
    "category": "music",
    "title": "Family Fun in the Midnight Sun",
    "time": "12p-5p",
    "ticketUrl": "https://www.facebook.com/events/1603728224071606/?acontext=%7B%22event_action_history%22%3A%5b%7B%22mechanism%22%3A%22discovery_custom_tab%22%2C%22surface%22%3A%22bookmark%22%7D%5d%2C%22ref_notif_type%22%3Anull%7D",
    "cost": ""
  },
  {
    "id": "45649",
    "date": "2026-06-24",
    "city": "Moose Pass",
    "venue": "Mile 29.5 Seward Hwy",
    "category": "festival",
    "title": "2026 Moose Pass Summer Solstice Festival",
    "time": "12p-9p",
    "ticketUrl": "https://www.facebook.com/moosepasssummersolsticefestival",
    "cost": ""
  },
  {
    "id": "47369",
    "date": "2026-08-05",
    "city": "Moose Pass",
    "venue": "Nikiski High School",
    "category": "music",
    "title": "Nikiski Days 2026: Industry Days",
    "time": "11a-?",
    "ticketUrl": "https://www.facebook.com/events/3436058973227523/?acontext=%7B%22event_action_history%22%3A%5b%7B%22mechanism%22%3A%22discovery_custom_tab%22%2C%22surface%22%3A%22bookmark%22%7D%5d%2C%22ref_notif_type%22%3Anull%7D",
    "cost": ""
  }
]
